name: Weather Data Automation

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-weather:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install requests pandas pytz
             
      - name: Run weather script
        env:
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
        run: python Weather1.py

      - name: Commit CSV back to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          echo "Listing files before commit:"
          ls -R
      
          git add .
          git commit -m "Auto-update weather data" || echo "No changes to commit"
          git push
      
